[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/organisations/independent/"
to = "/instances/independent/"

[[redirects]]
from = "/organisations/open-food-network-uk/"
to = "/instances/open-food-network-uk/"

[[redirects]]
from = "/organisations/open-food-network-deutschland/"
to = "/instances/open-food-network-deutschland/"

[[redirects]]
from = "/organisations/open-food-network-scandinavia/"
to = "/instances/open-food-network-scandinavia/"

[[redirects]]
from = "/organisations/acik-gida-agi/"
to = "/instances/acik-gida-agi/"

[[redirects]]
from = "/equipe/"
to = "/team/"

[[redirects]]
from = "/organisations/open-food-network-schweiz-suisse-svizzera/"
to = "/instances/open-food-network-schweiz-suisse-svizzera/"

[[redirects]]
from = "/equipe/kirsten-larsen/"
to = "/team/kirsten-larsen/"

[[redirects]]
from = "/organisations/open-food-network-katuma/"
to = "/instances/open-food-network-katuma/"

[[redirects]]
from = "/equipe/konrad-sachse/"
to = "/team/konrad-sachse/"

[[redirects]]
from = "/organisations/"
to = "/instances/"

[[redirects]]
from = "/organisations/open-food-network-greece/"
to = "/instances/open-food-network-greece/"

[[redirects]]
from = "/actualites/"
to = "/news/"

[[redirects]]
from = "/organisations/the-guardian/"
to = "/instances/the-guardian/"

[[redirects]]
from = "/organisations/abc-news/"
to = "/instances/abc-news/"

[[redirects]]
from = "/organisations/the-conversation/"
to = "/instances/the-conversation/"

[[redirects]]
from = "/organisations/open-food-france/"
to = "/instances/open-food-france/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/team/equipe-editoriale/"

[[redirects]]
from = "/organisations/open-food-network-italy/"
to = "/instances/open-food-network-italy/"

[[redirects]]
from = "/equipe/jo-da-silva/"
to = "/team/jo-da-silva/"

[[redirects]]
from = "/organisations/good-food/"
to = "/instances/good-food/"

[[redirects]]
from = "/organisations/the-weekly-times/"
to = "/instances/the-weekly-times/"

[[redirects]]
from = "/equipe/filipe-furtado/"
to = "/team/filipe-furtado/"

[[redirects]]
from = "/organisations/treehugger/"
to = "/instances/treehugger/"

[[redirects]]
from = "/organisations/open-food-network-ireland/"
to = "/instances/open-food-network-ireland/"

[[redirects]]
from = "/organisations/bbc/"
to = "/instances/bbc/"

[[redirects]]
from = "/equipe/david-cook/"
to = "/team/david-cook/"

